version: '3.6'
services:
  payment_microservice:
    container_name: payment_microservice
    build: .
    ports:
      - "0.0.0.0:50051:50051"
    networks:
      - internal
    hostname: payment_microservice

networks:
  internal:
    name: internal
    external: true