# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/payment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/payment.proto\"D\n\x14ResultPaymentRequest\x12\x1b\n\x13merchant_password_2\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\t\"\'\n\x15ResultPaymentResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"3\n\x1bGeneratePaymentLinkResponse\x12\x14\n\x0cpayment_link\x18\x01 \x01(\t\"\xb4\x01\n\x1aGeneratePaymentLinkRequest\x12\x16\n\x0emerchant_login\x18\x01 \x01(\t\x12\x1b\n\x13merchant_password_1\x18\x02 \x01(\t\x12\x0c\n\x04\x63ost\x18\x03 \x01(\x01\x12\x0e\n\x06number\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0f\n\x07is_test\x18\x06 \x01(\x05\x12\x1d\n\x15robokassa_payment_url\x18\x07 \x01(\t2\xa2\x01\n\x0ePaymentService\x12>\n\rResultPayment\x12\x15.ResultPaymentRequest\x1a\x16.ResultPaymentResponse\x12P\n\x13GeneratePaymentLink\x12\x1b.GeneratePaymentLinkRequest\x1a\x1c.GeneratePaymentLinkResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RESULTPAYMENTREQUEST']._serialized_start=23
  _globals['_RESULTPAYMENTREQUEST']._serialized_end=91
  _globals['_RESULTPAYMENTRESPONSE']._serialized_start=93
  _globals['_RESULTPAYMENTRESPONSE']._serialized_end=132
  _globals['_GENERATEPAYMENTLINKRESPONSE']._serialized_start=134
  _globals['_GENERATEPAYMENTLINKRESPONSE']._serialized_end=185
  _globals['_GENERATEPAYMENTLINKREQUEST']._serialized_start=188
  _globals['_GENERATEPAYMENTLINKREQUEST']._serialized_end=368
  _globals['_PAYMENTSERVICE']._serialized_start=371
  _globals['_PAYMENTSERVICE']._serialized_end=533
# @@protoc_insertion_point(module_scope)
